### ISSUE TITLE
 The IP pool is mainly sourced from users of HolaVPN

### ISSUE THREAD

**Issue by gidoneli** [niespodd/browser-fingerprinting#10]
This claim about Bright Data is false and misleading. Why are you being so antagonistic?

**Comment by clouedoc** [comment]
There is no need to take such a tone. No-one likes to wake up to aggressive emails.

However, I believe that you are right. I don't see such a big company relying only on one source for their IPs.

I believe it's a mix of:

- Incentivized IP sharing apps
- Mobile apps using the BrightData SDK as a monetization platform
- HolaVPN

I don't remember everything and this is a fast moving industry, but I believe a good starting point would be [this paper](https://github.com/prescience-data/dark-knowledge/blob/main/library/2021%20-%20Your%20Phone%20is%20My%20Proxy%20-%20Detecting%20and%20Understanding%20Mobile%20Proxy%20Networks.pdf)

**Comment by niespodd** [comment]
Hi @gidoneli 

Let me elaborate.

> This claim about Bright Data is false and misleading. 

This statement is based on the research linked by @clouedoc and I am about to do another, similar study with broader range of proxy sellers to make an up-to-date comparison in terms of quality, sourcing strategy, reliability et cetera. If you have any deeper insights into how Bright Data is sourcing it's IP pool I am happy to have a chat with you, and update the information accordingly.

It is known that Bright Data/Luminati use(d) to source their residential proxy pool largely via free VPN products. Same practice has been observed with Smartproxy and Oxylabs.

Below I listed some more resources on how popular providers source their residential IP pools (that are known to the public; links I had accumulated over around a year):
* Luminati (now Bright Data) - [Mobdro: Luminati Proxy Service “Suspended Service” To Pirate App](https://torrentfreak.com/mobdro-luminati-proxy-service-suspended-service-to-pirate-app-210315/)
* Oxylabs [Oxylabs Signs Exclusive Contract with Honeygain](https://finance.yahoo.com/news/oxylabs-signs-exclusive-contract-honeygain-140000269.html)
* Luminati (now Bright Data) - [Free VPN turns users' systems into exit nodes that could be abused by cybercriminals](https://www.techradar.com/uk/news/trend-micro-labels-free-holavpn-as-unsafe)
* ["NordVPN is linked closely with a Lithuanian data mining company called Tesonet. NordVPN is said to be one of Tesonet’s projects, Oxylabs.io is another one."](http://web.archive.org/web/20191128170008/https://medium.com/@derek./how-is-nordvpn-unblocking-disney-6c51045dbc30)
* PacketStream [How to Make MORE MONEY with PacketStream](https://blog.packetstream.io/How-to-Make-MORE-MONEY/)
* Oxylabs via SDK from mobile apps like [Currency Converter X](http://vsxapps.com/privacy/) - not anymore apparently (?)

Additionally, there is some amazing and popular enough write-ups from Spur Intelligence I highly recommend:
* [Proxy Diversity (or lack of)](https://medium.com/spur-intelligence/proxy-diversity-or-lack-of-5d7047d89a3c)
* [Residential Proxies: The “Legal” Botnet That Nobody Talks About](https://medium.com/spur-intelligence/residential-proxies-the-legal-botnet-that-nobody-talks-about-4470cae7e3c)
